//
// Created by Immanuel Bierer on 5/4/2025.
//

#ifndef LIVEWALLPAPER05_FLIPFLUIDSIMULATION_H
#define LIVEWALLPAPER05_FLIPFLUIDSIMULATION_H


using std::to_string;

class FlipFluidSimulation : public Simulation {
public:

    static const int NUM_CACHE_CHUNKS = 4600 / 8;

    static const int PARTICLES_PER_CHUNK = 8;

    static const int COUNT = NUM_CACHE_CHUNKS * PARTICLES_PER_CHUNK;

    static const int DEFAULT_INDEX_BUFFER_BINDING = 0;

    static const int OFFSET_ATTRIBUTE_LOCATION = 2;

    static const int VELOCITY_ATTRIBUTE_LOCATION = 3;

    struct ParticleInfo : Particle {

        int cellParticleId;

    };

    struct fCell {

        vec3 uvw;       // Combined velocity field

        vec3 duvw;      // Combined velocity change

        vec3 prevUVW;   // Combined previous velocity

        float p;

        float s;

        int cellType;

        float particleDensity;

    };

    struct pCell {

        int numCellParticles; // Max = 6

        int firstCellParticle;

    };

    struct __attribute__((aligned(128))) cacheChunk {
        ParticleInfo particles[PARTICLES_PER_CHUNK];
        float padding[(256 - sizeof(particles)) / sizeof(float)];
    };

    struct __attribute__((aligned(128))) cacheChunk1 {
        fCell particles[PARTICLES_PER_CHUNK];
        float padding[(512 - sizeof(particles)) / sizeof(float)];
    };

    struct __attribute__((aligned(128))) cacheChunk2 {
        pCell particles[PARTICLES_PER_CHUNK];
        float padding[(128 - sizeof(particles)) / sizeof(float)];
    };

    struct __attribute__((aligned(128))) FlipFluidSimulationData {
        union {
            //Particle stars[COUNT]; // CPU computation data
            cacheChunk chunks[NUM_CACHE_CHUNKS]; // GPU computation data
            cacheChunk1 chunks1[NUM_CACHE_CHUNKS]; // GPU computation data
            cacheChunk2 chunks2[NUM_CACHE_CHUNKS]; // GPU computation data
        };
    };

    // https://community.arm.com/developer/tools-software/graphics/b/blog/posts/get-started-with-compute-shaders
    string computeShaderCode[1000] = {
            View::ES_VERSION,
            "const uint PARTICLES_PER_CHUNK = " + to_string(PARTICLES_PER_CHUNK) + "u;",
            "const uint NUM_CACHE_CHUNKS = uint(" + to_string(NUM_CACHE_CHUNKS) + ");\n",
            "const uint COUNT = " + to_string(COUNT) + "u;\n",
            "struct ParticleInfo {\n",
            "    vec3 position;\n",
            "    vec3 velocity;\n",
            "    int cellParticleId;\n",
            "};\n",
            "struct fCell {\n",
            "    vec3 uvw;       // Combined velocity field\n",
            "    vec3 duvw;      // Combined velocity change\n",
            "    vec3 prevUVW;   // Combined previous velocity\n",
            "    float p;\n",
            "    float s;\n",
            "    int cellType;\n",
            "    float particleDensity;\n",
            "};\n",
            "struct pCell {\n",
            "    int numCellParticles; // Max = 6\n",
            "    int firstCellParticle;\n",
            "};\n",
            "struct cacheChunk {\n",
            "    ParticleInfo stars[" + to_string(PARTICLES_PER_CHUNK) + "];\n",
            "    float padding[" + to_string((int)sizeof(cacheChunk::padding) / sizeof(float)) + "];\n",
            "};\n",
            "struct cacheChunk1 {\n",
            "    fCell stars[" + to_string(PARTICLES_PER_CHUNK) + "];\n",
            "    float padding[" + to_string((int)sizeof(cacheChunk1::padding) / sizeof(float)) + "];\n",
            "};\n",
            "struct cacheChunk2 {\n",
            "    pCell stars[" + to_string(PARTICLES_PER_CHUNK) + "];\n",
            "    float padding[" + to_string((int)sizeof(cacheChunk2::padding) / sizeof(float)) + "];\n",
            "};\n",
            "layout(packed, binding = " + to_string(DEFAULT_INDEX_BUFFER_BINDING) + ") buffer destBuffer {\n",
            "	  cacheChunk chunks[" + to_string(NUM_CACHE_CHUNKS) + "];\n",
            "	  cacheChunk1 chunks1[" + to_string(NUM_CACHE_CHUNKS) + "];\n",
            "	  cacheChunk2 chunks2[" + to_string(NUM_CACHE_CHUNKS) + "];\n",
            "} outBuffer;\n",
            "uniform float t;\n",
            "layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;\n",
            "void main(){\n",
            "    uint task = gl_WorkGroupSize.x * gl_LocalInvocationID.x + gl_LocalInvocationID.y;\n",
            "    if(task >= NUM_CACHE_CHUNKS){\n",
            "        return;\n",
            "    }\n",
            "    vec3 gravitySum[PARTICLES_PER_CHUNK];\n",
            "    for(uint i = 0u; i < PARTICLES_PER_CHUNK; i++){\n",
            "        gravitySum[i] = vec3(0.0f, 0.0f, 0.0f);\n",
            "        for(uint j = 0u; j < NUM_CACHE_CHUNKS; j++){\n",
            "            for(uint k = 0u; k < PARTICLES_PER_CHUNK; k++){\n",
            "                if(PARTICLES_PER_CHUNK * j + k == PARTICLES_PER_CHUNK * task + i)\n",
            "                    continue;\n",
            "                vec3 difference = outBuffer.chunks[j].stars[k].position - outBuffer.chunks[task].stars[i].position;\n",
            "                float differenceSquared = dot(difference, difference);\n",
            "                float distance = sqrt(differenceSquared);\n",
            "                gravitySum[i] += difference / distance / differenceSquared;\n",
            "            }\n",
            "        }\n",
            "    }\n",
            "    barrier();\n",
            "    for(uint i = 0u; i < PARTICLES_PER_CHUNK; i++){\n",
            "        outBuffer.chunks[task].stars[i].velocity += gravitySum[i];\n",
            "        outBuffer.chunks[task].stars[i].position += outBuffer.chunks[task].stars[i].velocity;\n",
            "    }\n",
            "}\n",
            /*"\n",
            "const uint PARTICLES_PER_CHUNK = " + to_string(PARTICLES_PER_CHUNK) + "u;",
            "const uint NUM_CACHE_CHUNKS = uint(" + to_string(NUM_CACHE_CHUNKS) + ");\n",
            "const uint COUNT = " + to_string(COUNT) + "u;\n",
            "struct Particle {\n",
            "    vec3 position;\n",
            "    vec3 velocity;\n",
            "};\n",
            "struct cacheChunk {\n",
            "    Particle stars[" + to_string(PARTICLES_PER_CHUNK) + "];\n",
            "    float padding[" + to_string((int)sizeof(cacheChunk::padding) / sizeof(float)) + "];\n",
            "};\n",
            "layout(packed, binding = " + to_string(DEFAULT_INDEX_BUFFER_BINDING) + ") buffer destBuffer {\n",
            "	  cacheChunk chunks[" + to_string(NUM_CACHE_CHUNKS) + "];\n",
            "} outBuffer;\n",
            "\n",
            "void integrateParticles(const float &_dt, const vec3 &_gravity)\n",
            "{\n",
            "    for (int i = 0; i < numParticles; i++) {\n",
            "        particleVel[i] += _dt * _gravity;\n",
            "        particlePos[i] += particleVel[i] * _dt;\n",
            "    }\n",
            "}\n",
            "\n",
            "void pushParticlesApart(const float& _numIters)\n",
            "{\n",
            "    float colorDiffusionCoeff = 0.001;\n",
            "    \n",
            "    // particleCount stars per cell\n",
            "    \n",
            "    for (int i = 0; i < pNumCells; i++)\n",
            "        numCellParticles[i] = 0;\n",
            "    \n",
            "    for (int i = 0; i < numParticles; i++) {\n",
            "        float x = particlePos[i].x;\n",
            "        float y = particlePos[i].y;\n",
            "        float z = particlePos[i].z;\n",
            "        \n",
            "        int xi = clamp(floor(x * pInvSpacing), 0.0f, float(pNumX - 1));\n",
            "        int yi = clamp(floor(y * pInvSpacing), 0.0f, float(pNumY - 1));\n",
            "        int zi = clamp(floor(z * pInvSpacing), 0.0f, float(pNumZ - 1));\n",
            "        int cellNr = xi * pNumY * pNumZ + yi * pNumZ + zi;\n",
            "        numCellParticles[cellNr]++;\n",
            "    }\n",
            "    \n",
            "    // partial sums\n",
            "    \n",
            "    int first = 0;\n",
            "    \n",
            "    for (int i = 0; i < pNumCells; i++) {\n",
            "        first += numCellParticles[i];\n",
            "        firstCellParticle[i] = first;\n",
            "    }\n",
            "    firstCellParticle[pNumCells] = first; // guard\n",
            "    \n",
            "    // fill stars into cells\n",
            "    \n",
            "    for (int i = 0; i < numParticles; i++) {\n",
            "        float x = particlePos[i].x;\n",
            "        float y = particlePos[i].y;\n",
            "        float z = particlePos[i].z;\n",
            "        \n",
            "        int xi = clamp(floor(x * pInvSpacing), 0.0f, float(pNumX - 1));\n",
            "        int yi = clamp(floor(y * pInvSpacing), 0.0f, float(pNumY - 1));\n",
            "        int zi = clamp(floor(z * pInvSpacing), 0.0f, float(pNumZ - 1));\n",
            "        int cellNr = xi * pNumY * pNumZ + yi * pNumZ + zi;\n",
            "        firstCellParticle[cellNr]--;\n",
            "        cellParticleIds[firstCellParticle[cellNr]] = i;\n",
            "    }\n",
            "    \n",
            "    // push stars apart\n",
            "    \n",
            "    float minDist = 2.0 * particleRadius;\n",
            "    float minDist2 = minDist * minDist;\n",
            "    \n",
            "    for (int iter = 0; iter < _numIters; iter++) {\n",
            "        \n",
            "        for (int i = 0; i < numParticles; i++) {\n",
            "            float px = particlePos[i].x;\n",
            "            float py = particlePos[i].y;\n",
            "            float pz = particlePos[i].z;\n",
            "            \n",
            "            int pxi = floor(px * pInvSpacing);\n",
            "            int pyi = floor(py * pInvSpacing);\n",
            "            int pzi = floor(pz * pInvSpacing);\n",
            "            int x0 = max(pxi - 1, 0);\n",
            "            int y0 = max(pyi - 1, 0);\n",
            "            int z0 = max(pzi - 1, 0);\n",
            "            int x1 = min(pxi + 1, pNumX - 1);\n",
            "            int y1 = min(pyi + 1, pNumY - 1);\n",
            "            int z1 = min(pzi + 1, pNumZ - 1);\n",
            "            \n",
            "            for (int xi = x0; xi <= x1; xi++) {\n",
            "                for (int yi = y0; yi <= y1; yi++) {\n",
            "                    for (int zi = z0; zi <= z1; zi++) {\n",
            "                        int cellNr = xi * pNumY * pNumZ + yi * pNumZ + zi;\n",
            "                        int first = firstCellParticle[cellNr];\n",
            "                        int last = firstCellParticle[cellNr + 1];\n",
            "                        for (int j = first; j < last; j++) {\n",
            "                            int id = cellParticleIds[j];\n",
            "                            if (id == i)\n",
            "                                continue;\n",
            "                            float qx = particlePos[id].x;\n",
            "                            float qy = particlePos[id].y;\n",
            "                            float qz = particlePos[id].z;\n",
            "                            \n",
            "                            float dx = qx - px;\n",
            "                            float dy = qy - py;\n",
            "                            float dz = qz - pz;\n",
            "                            float d2 = dx * dx + dy * dy + dz * dz;\n",
            "                            if (d2 > minDist2 || d2 == 0.0)\n",
            "                                continue;\n",
            "                            float d = sqrt(d2);\n",
            "                            float s = 0.5 * (minDist - d) / d;\n",
            "                            dx *= s;\n",
            "                            dy *= s;\n",
            "                            dz *= s;\n",
            "                            particlePos[i].x -= dx;\n",
            "                            particlePos[i].y -= dy;\n",
            "                            particlePos[i].z -= dz;\n",
            "                            particlePos[id].x += dx;\n",
            "                            particlePos[id].y += dy;\n",
            "                            particlePos[id] += dz;\n",
            "                            \n",
            "                            // diffuse colors\n",
            "                            \n",
            "                            for (int k = 0; k < 3; k++) {\n",
            "                                float color0 = particleColor[i].v[k];\n",
            "                                float color1 = particleColor[id].v[k];\n",
            "                                float color = (color0 + color1) * 0.5;\n",
            "                                particleColor[i].v[k] = color0 + (color - color0) * colorDiffusionCoeff;\n",
            "                                particleColor[id].v[k] = color1 + (color - color1) * colorDiffusionCoeff;\n",
            "                            }\n",
            "                        }\n",
            "                    }\n",
            "                }\n",
            "            }\n",
            "        }\n",
            "    }\n",
            "}\n",
            "\n",
            "void handleParticleCollisions()\n",
            "{\n",
            "    float r = particleRadius;\n",
            "    \n",
            "    float minX = h + r;\n",
            "    float maxX = (fNumX - 1) * h - r;\n",
            "    float minY = h + r;\n",
            "    float maxY = (fNumY - 1) * h - r;\n",
            "    float minZ = h + r;\n",
            "    float maxZ = (fNumZ - 1) * h - r;\n",
            "    \n",
            "    for (int i = 0; i < numParticles; i++) {\n",
            "        float x = particlePos[i].x;\n",
            "        float y = particlePos[i].y;\n",
            "        float z = particlePos[i].z;\n",
            "        \n",
            "        // wall collisions\n",
            "        \n",
            "        if (x < minX) {\n",
            "            x = minX;\n",
            "            particleVel[i].x = 0.0;\n",
            "        }\n",
            "        if (x > maxX) {\n",
            "            x = maxX;\n",
            "            particleVel[i].x = 0.0;\n",
            "        }\n",
            "        if (y < minY) {\n",
            "            y = minY;\n",
            "            particleVel[i].y = 0.0;\n",
            "        }\n",
            "        if (y > maxY) {\n",
            "            y = maxY;\n",
            "            particleVel[i].y = 0.0;\n",
            "        }\n",
            "        if (z < minZ) {\n",
            "            z = minZ;\n",
            "            particleVel[i].z = 0.0;\n",
            "        }\n",
            "        if (z > maxZ) {\n",
            "            z = maxZ;\n",
            "            particleVel[i].z = 0.0;\n",
            "        }\n",
            "        particlePos[i].x = x;\n",
            "        particlePos[i].y = y;\n",
            "        particlePos[i].z = z;\n",
            "    }\n",
            "\n",
            "}\n",
            "\n",
            "void updateParticleDensity()\n",
            "{\n",
            "    int n = fNumY;\n",
            "    float h1 = fInvSpacing;\n",
            "    float h2 = 0.5 * h;\n",
            "    \n",
            "    float* d = particleDensity;\n",
            "    \n",
            "    for (int i = 0; i < fNumCells; i++)\n",
            "        d[i] = 0.0;\n",
            "    \n",
            "    for (int i = 0; i < numParticles; i++) {\n",
            "        float x = particlePos[i].x;\n",
            "        float y = particlePos[i].y;\n",
            "        float z = particlePos[i].z;\n",
            "        \n",
            "        x = clamp(x, h, (fNumX - 1) * h);\n",
            "        y = clamp(y, h, (fNumY - 1) * h);\n",
            "        z = clamp(z, h, (fNumZ - 1) * h);\n",
            "        \n",
            "        int x0 = floor((x - h2) * h1);\n",
            "        float tx = ((x - h2) - x0 * h) * h1;\n",
            "        int x1 = min(x0 + 1, fNumX - 2);\n",
            "        \n",
            "        int y0 = floor((y - h2) * h1);\n",
            "        float ty = ((y - h2) - y0 * h) * h1;\n",
            "        int y1 = min(y0 + 1, fNumY - 2);\n",
            "        \n",
            "        int z0 = floor((z - h2) * h1);\n",
            "        float tz = ((z - h2) - z0 * h) * h1;\n",
            "        int z1 = min(z0 + 1, fNumZ - 2);\n",
            "        \n",
            "        float sx = 1.0 - tx;\n",
            "        float sy = 1.0 - ty;\n",
            "        float sz = 1.0 - tz;\n",
            "        \n",
            "        if (x0 < fNumX && y0 < fNumY && z0 < fNumZ) d[x0 * (n * fNumZ) + y0 * fNumZ + z0] += sx * sy * sz;\n",
            "        if (x1 < fNumX && y0 < fNumY && z0 < fNumZ) d[x1 * (n * fNumZ) + y0 * fNumZ + z0] += tx * sy * sz;\n",
            "        if (x1 < fNumX && y1 < fNumY && z0 < fNumZ) d[x1 * (n * fNumZ) + y1 * fNumZ + z0] += tx * ty * sz;\n",
            "        if (x0 < fNumX && y1 < fNumY && z0 < fNumZ) d[x0 * (n * fNumZ) + y1 * fNumZ + z0] += sx * ty * sz;\n",
            "        if (x0 < fNumX && y0 < fNumY && z1 < fNumZ) d[x0 * (n * fNumZ) + y0 * fNumZ + z1] += sx * sy * tz;\n",
            "        if (x1 < fNumX && y0 < fNumY && z1 < fNumZ) d[x1 * (n * fNumZ) + y0 * fNumZ + z1] += tx * sy * tz;\n",
            "        if (x1 < fNumX && y1 < fNumY && z1 < fNumZ) d[x1 * (n * fNumZ) + y1 * fNumZ + z1] += tx * ty * tz;\n",
            "        if (x0 < fNumX && y1 < fNumY && z1 < fNumZ) d[x0 * (n * fNumZ) + y1 * fNumZ + z1] += sx * ty * tz;\n",
            "    }\n",
            "\n",
            "    if (particleRestDensity == 0.0) {\n",
            "        float sum = 0.0;\n",
            "        int numFluidCells = 0;\n",
            "        \n",
            "        for (int i = 0; i < fNumCells; i++) {\n",
            "            if (cellType[i] == FLUID_CELL) {\n",
            "                sum += d[i];\n",
            "                numFluidCells++;\n",
            "            }\n",
            "        }\n",
            "        \n",
            "        if (numFluidCells > 0)\n",
            "            particleRestDensity = sum / numFluidCells;\n",
            "    }\n",
            "}\n",
            "\n",
            "void transferVelocities(const bool& _toGrid, const float& _flipRatio)\n",
            "{\n",
            "    int n = fNumY;\n",
            "    float h1 = fInvSpacing;\n",
            "    float h2 = 0.5f * h;\n",
            "    \n",
            "    if (_toGrid) {\n",
            "        for (int i = 0; i < fNumCells; i++) {\n",
            "            prevU[i] = u[i];\n",
            "            prevV[i] = v[i];\n",
            "            prevW[i] = w[i];\n",
            "        }\n",
            "        \n",
            "        for (int i = 0; i < fNumCells; i++) {\n",
            "            du[i] = 0.0;\n",
            "            dv[i] = 0.0;\n",
            "            dw[i] = 0.0;\n",
            "            u[i] = 0.0;\n",
            "            v[i] = 0.0;\n",
            "            w[i] = 0.0;\n",
            "        }\n",
            "        \n",
            "        for (int i = 0; i < fNumCells; i++)\n",
            "            cellType[i] = s[i] == 0.0 ? SOLID_CELL : AIR_CELL;\n",
            "        \n",
            "        for (int i = 0; i < numParticles; i++) {\n",
            "            float x = particlePos[i].x;\n",
            "            float y = particlePos[i].y;\n",
            "            float z = particlePos[i].z;\n",
            "            \n",
            "            int xi = clamp(floor(x * h1), 0.0f, float(fNumX - 1));\n",
            "            int yi = clamp(floor(y * h1), 0.0f, float(fNumY - 1));\n",
            "            int zi = clamp(floor(z * h1), 0.0f, float(fNumZ - 1));\n",
            "            \n",
            "            int cellNr = xi * (n * fNumZ) + yi * fNumZ + zi;\n",
            "            if (cellType[cellNr] == AIR_CELL)\n",
            "                cellType[cellNr] = FLUID_CELL;\n",
            "        }\n",
            "    }\n",
            "    \n",
            "    for (int component = 0; component < 3; component++) {\n",
            "        float dx = (component == 0) ? 0.0 : h2;\n",
            "        float dy = (component == 1) ? 0.0 : h2;\n",
            "        float dz = (component == 2) ? 0.0 : h2;\n",
            "        \n",
            "        float* f = (component == 0) ? u : ((component == 1) ? v : w);\n",
            "        float* prevF = (component == 0) ? prevU : ((component == 1) ? prevV : prevW);\n",
            "        float* d = (component == 0) ? du : ((component == 1) ? dv : dw);\n",
            "        \n",
            "        for (int i = 0; i < numParticles; i++) {\n",
            "            float x = particlePos[i].x;\n",
            "            float y = particlePos[i].y;\n",
            "            float z = particlePos[i].z;\n",
            "            \n",
            "            x = clamp(x, h, (fNumX - 1) * h);\n",
            "            y = clamp(y, h, (fNumY - 1) * h);\n",
            "            z = clamp(z, h, (fNumZ - 1) * h);\n",
            "            \n",
            "            int x0 = min<float>(floor((x - dx) * h1), fNumX - 2);\n",
            "            float tx = ((x - dx) - x0 * h) * h1;\n",
            "            int x1 = min(x0 + 1, fNumX - 2);\n",
            "            \n",
            "            int y0 = min<float>(floor((y - dy) * h1), fNumY - 2);\n",
            "            float ty = ((y - dy) - y0 * h) * h1;\n",
            "            int y1 = min(y0 + 1, fNumY - 2);\n",
            "            \n",
            "            int z0 = min<float>(floor((z - dz) * h1), fNumZ - 2);\n",
            "            float tz = ((z - dz) - z0 * h) * h1;\n",
            "            int z1 = min(z0 + 1, fNumZ - 2);\n",
            "            \n",
            "            float sx = 1.0 - tx;\n",
            "            float sy = 1.0 - ty;\n",
            "            float sz = 1.0 - tz;\n",
            "            \n",
            "            float d0 = sx * sy * sz;\n",
            "            float d1 = tx * sy * sz;\n",
            "            float d2 = tx * ty * sz;\n",
            "            float d3 = sx * ty * sz;\n",
            "            float d4 = sx * sy * tz;\n",
            "            float d5 = tx * sy * tz;\n",
            "            float d6 = tx * ty * tz;\n",
            "            float d7 = sx * ty * tz;\n",
            "            \n",
            "            int nr0 = x0 * (n * fNumZ) + y0 * fNumZ + z0;\n",
            "            int nr1 = x1 * (n * fNumZ) + y0 * fNumZ + z0;\n",
            "            int nr2 = x1 * (n * fNumZ) + y1 * fNumZ + z0;\n",
            "            int nr3 = x0 * (n * fNumZ) + y1 * fNumZ + z0;\n",
            "            int nr4 = x0 * (n * fNumZ) + y0 * fNumZ + z1;\n",
            "            int nr5 = x1 * (n * fNumZ) + y0 * fNumZ + z1;\n",
            "            int nr6 = x1 * (n * fNumZ) + y1 * fNumZ + z1;\n",
            "            int nr7 = x0 * (n * fNumZ) + y1 * fNumZ + z1;\n",
            "            \n",
            "            if (_toGrid) {\n",
            "                float pv = particleVel[i].v[component];\n",
            "                f[nr0] += pv * d0; d[nr0] += d0;\n",
            "                f[nr1] += pv * d1; d[nr1] += d1;\n",
            "                f[nr2] += pv * d2; d[nr2] += d2;\n",
            "                f[nr3] += pv * d3; d[nr3] += d3;\n",
            "                f[nr4] += pv * d4; d[nr4] += d4;\n",
            "                f[nr5] += pv * d5; d[nr5] += d5;\n",
            "                f[nr6] += pv * d6; d[nr6] += d6;\n",
            "                f[nr7] += pv * d7; d[nr7] += d7;\n",
            "            }\n",
            "            else {\n",
            "                int offset = (component == 0) ? (n * fNumZ) : ((component == 1) ? fNumZ : 1);\n",
            "                \n",
            "                float valid0 = (cellType[nr0] != AIR_CELL || cellType[nr0 - offset] != AIR_CELL) ? 1.0 : 0.0;\n",
            "                float valid1 = (cellType[nr1] != AIR_CELL || cellType[nr1 - offset] != AIR_CELL) ? 1.0 : 0.0;\n",
            "                float valid2 = (cellType[nr2] != AIR_CELL || cellType[nr2 - offset] != AIR_CELL) ? 1.0 : 0.0;\n",
            "                float valid3 = (cellType[nr3] != AIR_CELL || cellType[nr3 - offset] != AIR_CELL) ? 1.0 : 0.0;\n",
            "                float valid4 = (cellType[nr4] != AIR_CELL || cellType[nr4 - offset] != AIR_CELL) ? 1.0 : 0.0;\n",
            "                float valid5 = (cellType[nr5] != AIR_CELL || cellType[nr5 - offset] != AIR_CELL) ? 1.0 : 0.0;\n",
            "                float valid6 = (cellType[nr6] != AIR_CELL || cellType[nr6 - offset] != AIR_CELL) ? 1.0 : 0.0;\n",
            "                float valid7 = (cellType[nr7] != AIR_CELL || cellType[nr7 - offset] != AIR_CELL) ? 1.0 : 0.0;\n",
            "                \n",
            "                float v = particleVel[i].v[component];\n",
            "                float d = valid0 * d0 + valid1 * d1 + valid2 * d2 + valid3 * d3 +\n",
            "                          valid4 * d4 + valid5 * d5 + valid6 * d6 + valid7 * d7;\n",
            "                \n",
            "                if (d > 0.0) {\n",
            "                    float picV = (valid0 * d0 * f[nr0] + valid1 * d1 * f[nr1] + valid2 * d2 * f[nr2] + valid3 * d3 * f[nr3] +\n",
            "                                  valid4 * d4 * f[nr4] + valid5 * d5 * f[nr5] + valid6 * d6 * f[nr6] + valid7 * d7 * f[nr7]) / d;\n",
            "                    float corr = (valid0 * d0 * (f[nr0] - prevF[nr0]) + valid1 * d1 * (f[nr1] - prevF[nr1]) +\n",
            "                                  valid2 * d2 * (f[nr2] - prevF[nr2]) + valid3 * d3 * (f[nr3] - prevF[nr3]) +\n",
            "                                  valid4 * d4 * (f[nr4] - prevF[nr4]) + valid5 * d5 * (f[nr5] - prevF[nr5]) +\n",
            "                                  valid6 * d6 * (f[nr6] - prevF[nr6]) + valid7 * d7 * (f[nr7] - prevF[nr7])) / d;\n",
            "                    float flipV = v + corr;\n",
            "                    \n",
            "                    particleVel[i].v[component] = (1.0 - _flipRatio) * picV + _flipRatio * flipV;\n",
            "                }\n",
            "            }\n",
            "        }\n",
            "        \n",
            "        if (_toGrid) {\n",
            "            for (int i = 0; i < fNumCells; i++) {\n",
            "                if (d[i] > 0.0)\n",
            "                    f[i] /= d[i];\n",
            "            }\n",
            "            \n",
            "            // Restore solid cells\n",
            "            for (int i = 0; i < fNumX; i++) {\n",
            "                for (int j = 0; j < fNumY; j++) {\n",
            "                    for (int k = 0; k < fNumZ; k++) {\n",
            "                        int solid = cellType[i * (n * fNumZ) + j * fNumZ + k] == SOLID_CELL;\n",
            "                        if (solid || (i > 0 && cellType[(i - 1) * (n * fNumZ) + j * fNumZ + k] == SOLID_CELL))\n",
            "                            u[i * (n * fNumZ) + j * fNumZ + k] = 0.0;\n",
            "                        if (solid || (j > 0 && cellType[i * (n * fNumZ) + (j - 1) * fNumZ + k] == SOLID_CELL))\n",
            "                            v[i * (n * fNumZ) + j * fNumZ + k] = 0.0;\n",
            "                        if (solid || (k > 0 && cellType[i * (n * fNumZ) + j * fNumZ + (k - 1)] == SOLID_CELL))\n",
            "                            w[i * (n * fNumZ) + j * fNumZ + k] = 0.0;\n",
            "                    }\n",
            "                }\n",
            "            }\n",
            "        }\n",
            "    }\n",
            "}\n",
            "\n",
            "void solveIncompressibility(const int& _numIters, const float& _dt, const float& _overRelaxation, const bool& _compensateDrift = true) {\n",
            "    for (int i = 0; i < fNumCells; i++) {\n",
            "        p[i] = 0.0;\n",
            "        prevU[i] = u[i];\n",
            "        prevV[i] = v[i];\n",
            "        prevW[i] = w[i];\n",
            "    }\n",
            "    \n",
            "    int n = fNumY;\n",
            "    float cp = density * h / _dt;\n",
            "    \n",
            "    for (int iter = 0; iter < _numIters; iter++) {\n",
            "        for (int i = 1; i < fNumX - 1; i++) {\n",
            "            for (int j = 1; j < fNumY - 1; j++) {\n",
            "                for (int k = 1; k < fNumZ - 1; k++) {\n",
            "                    \n",
            "                    if (cellType[i * (n * fNumZ) + j * fNumZ + k] != FLUID_CELL)\n",
            "                        continue;\n",
            "                    \n",
            "                    int center = i * (n * fNumZ) + j * fNumZ + k;\n",
            "                    int left = (i - 1) * (n * fNumZ) + j * fNumZ + k;\n",
            "                    int right = (i + 1) * (n * fNumZ) + j * fNumZ + k;\n",
            "                    int bottom = i * (n * fNumZ) + (j - 1) * fNumZ + k;\n",
            "                    int top = i * (n * fNumZ) + (j + 1) * fNumZ + k;\n",
            "                    int back = i * (n * fNumZ) + j * fNumZ + (k - 1);\n",
            "                    int front = i * (n * fNumZ) + j * fNumZ + (k + 1);\n",
            "                    \n",
            "                    float sx0 = s[left];\n",
            "                    float sx1 = s[right];\n",
            "                    float sy0 = s[bottom];\n",
            "                    float sy1 = s[top];\n",
            "                    float sz0 = s[back];\n",
            "                    float sz1 = s[front];\n",
            "                    float s = sx0 + sx1 + sy0 + sy1 + sz0 + sz1;\n",
            "                    \n",
            "                    if (s == 0.0)\n",
            "                        continue;\n",
            "                    \n",
            "                    float div = u[right] - u[center] + v[top] - v[center] + w[front] - w[center];\n",
            "                    \n",
            "                    if (particleRestDensity > 0.0 && _compensateDrift) {\n",
            "                        float _k = 1.0;\n",
            "                        float compression = particleDensity[i * (n * fNumZ) + j * fNumZ + k] - particleRestDensity;\n",
            "                        if (compression > 0.0)\n",
            "                            div = div - _k * compression;\n",
            "                    }\n",
            "                    \n",
            "                    float p = -div / s;\n",
            "                    p *= _overRelaxation;\n",
            "                    this->p[center] += cp * p;\n",
            "                    \n",
            "                    u[center] -= sx0 * p;\n",
            "                    u[right] += sx1 * p;\n",
            "                    v[center] -= sy0 * p;\n",
            "                    v[top] += sy1 * p;\n",
            "                    w[center] -= sz0 * p;\n",
            "                    w[front] += sz1 * p;\n",
            "                }\n",
            "            }\n",
            "        }\n",
            "    }\n",
            "}\n",
            "\n",
            "void simulate(const vec3 &_gravity)\n",
            "{\n",
            "    int numSubSteps = 1;\n",
            "    float sdt = dt / numSubSteps;\n",
            "    \n",
            "    for (int step = 0; step < numSubSteps; step++) {\n",
            "        this->integrateParticles(sdt, _gravity);\n",
            "        if (separateParticles)\n",
            "            this->pushParticlesApart(numParticleIters);\n",
            "        this->handleParticleCollisions();\n",
            "        this->transferVelocities(true, flipRatio);\n",
            "        this->updateParticleDensity();\n",
            "        this->solveIncompressibility(numPressureIters, sdt, overRelaxation, compensateDrift);\n",
            "        this->transferVelocities(false, flipRatio);\n",
            "    }\n",
            "    \n",
            "    //this->updateParticleColors();\n",
            "}\n",*/
    };

    FlipFluidSimulationData* data;

    double t;

    FlipFluidSimulation(){

    }

    ~FlipFluidSimulation(){

    }

    void initialize(const ComputationOptions& computationOption);

    void simulate(const int &iterations, bool pushDataToGPU, bool retrieveDataFromGPU);

    ComputationOptions getComputationOption();

    void pushData2GPU();

private:

    float dt;

    void simulateOnCPU();

    void simulateOnGPU(const int &iterations, bool pushDataToGPU, bool retrieveDataFromGPU);

    float getRandomFloat(float x);

    bool seed();

};


#endif //LIVEWALLPAPER05_FLIPFLUIDSIMULATION_H
